apiVersion: v1
kind: ServiceAccount
metadata:
  name: merchant-api
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-3" }
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: merchant-worker
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-3" }
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: merchant-portal
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-3" }
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: merchant-migration
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-3" }
automountServiceAccountToken: false
