apiVersion: v1
kind: Service
metadata:
  name: merchant-api
  namespace: merchant-platform
  labels:
    app.kubernetes.io/name: merchant-api
    app.kubernetes.io/part-of: merchant-platform
spec:
  selector:
    app.kubernetes.io/name: merchant-api
  ports:
    - { name: http, port: 8080, targetPort: http }
---
apiVersion: v1
kind: Service
metadata:
  name: merchant-worker-metrics
  namespace: merchant-platform
  labels:
    app.kubernetes.io/name: merchant-worker
    app.kubernetes.io/part-of: merchant-platform
spec:
  selector:
    app.kubernetes.io/name: merchant-worker
  ports:
    - { name: metrics, port: 9091, targetPort: metrics }
---
apiVersion: v1
kind: Service
metadata:
  name: merchant-portal
  namespace: merchant-platform
  labels:
    app.kubernetes.io/name: merchant-portal
    app.kubernetes.io/part-of: merchant-platform
spec:
  selector:
    app.kubernetes.io/name: merchant-portal
  ports:
    - { name: http, port: 3000, targetPort: http }

