apiVersion: v1
kind: ConfigMap
metadata:
  name: merchant-platform-config
  namespace: merchant-platform
data:
  NODE_ENV: production
  MYSQL_SSL_CA_PATH: /etc/ssl/certs/aws-rds-global-bundle.pem
  NOTIFICATION_PROVIDER: webhook
  RELEASE_VERSION: gitops-managed
