apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: merchant-api-runtime
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-2" }
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: merchant-api-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: merchant-platform/production/api
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: merchant-worker-runtime
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-2" }
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: merchant-worker-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: merchant-platform/production/worker
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: merchant-portal-runtime
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-2" }
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: merchant-portal-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: merchant-platform/production/portal
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: merchant-portal-oidc
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-2" }
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: merchant-portal-oidc
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: merchant-platform/production/portal-oidc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: merchant-migration-runtime
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-2" }
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: merchant-migration-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: merchant-platform/production/migration
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-routing
  namespace: merchant-platform
  annotations: { argocd.argoproj.io/sync-wave: "-2" }
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: alertmanager-routing
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: merchant-platform/production/alertmanager-routing
