apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secrets.yaml
  - ingress.yaml
  - network-policies.yaml
  - worker-scaling.yaml
patches:
  - path: config-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: merchant-api
    patch: |-
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/-
        value:
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: merchant-api
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: merchant-worker
    patch: |-
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/-
        value:
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: merchant-worker
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: merchant-portal
    patch: |-
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/-
        value:
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: merchant-portal
images:
  - name: merchant-api-image
    newName: REPLACE_ECR_REGISTRY/merchant-platform-api
    digest: sha256:REPLACE_API_DIGEST
  - name: merchant-worker-image
    newName: REPLACE_ECR_REGISTRY/merchant-platform-worker
    digest: sha256:REPLACE_WORKER_DIGEST
  - name: merchant-portal-image
    newName: REPLACE_ECR_REGISTRY/merchant-platform-portal
    digest: sha256:REPLACE_PORTAL_DIGEST
  - name: merchant-migration-image
    newName: REPLACE_ECR_REGISTRY/merchant-platform-migration
    digest: sha256:REPLACE_MIGRATION_DIGEST
