apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: merchant-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: merchant-platform
  source:
    repoURL: REPLACE_REPO_URL
    targetRevision: main
    path: REPLACE_GITOPS_PATH
  destination:
    server: https://kubernetes.default.svc
    namespace: merchant-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m

