prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 7d
    resources:
      requests: { cpu: 250m, memory: 768Mi }
      limits: { cpu: "1", memory: 1536Mi }
alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: merchant-platform
    alertmanagerConfigNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: merchant-platform
grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  resources:
    requests: { cpu: 100m, memory: 192Mi }
    limits: { cpu: 500m, memory: 512Mi }

