apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: merchant-api
  namespace: merchant-platform
  labels:
    app.kubernetes.io/part-of: merchant-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: merchant-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: merchant-worker
  namespace: merchant-platform
  labels:
    app.kubernetes.io/part-of: merchant-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: merchant-worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s

